---
AWSTemplateFormatVersion: 2010-09-09

Description:
  The template creates autoscaling group

Parameters:
  ImageID:
    Description: parameters for custom ec2 instance id
    Type: String
    Default: ami-06b21ccaeff8cd686
    AllowedValues:
      - ami-06b21ccaeff8cd686
      - ami-0866a3c8686eaeeba

  InstanceTYPE:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: webserverTemplate
      LaunchTemplateData:
        ImageId: !Ref ImageID
        InstanceType: !Ref InstanceTYPE
        UserData:
          Fn::Base64: 
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd.x86_64
              systemctl start httpd.service
              systemctl enable httpd.service
              echo "Hello from Hossain CloudFormation course with HOSSAIN Mohammad"
  AutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: HossainASG
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
      DesiredCapacity: 2
      MinSize: 1
      MaxSize: 2
      TargetGroupARNs: 
        - !Ref ApplicationLoadbalancerTargetgroup
      VPCZoneIdentifier: 
        - subnet-06569bb0f03247451
        - subnet-07b5fcdd494f8419f
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: "1"
  AutoscalLoadbalancer: 
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Subnets: 
        - subnet-06569bb0f03247451
        - subnet-07b5fcdd494f8419f
      Type: application
  ApplicationLoadbalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - TargetGroupArn: !Ref ApplicationLoadbalancerTargetgroup
          Type: forward
      LoadBalancerArn: !Ref AutoscalLoadbalancer
      Port: 80
      Protocol: HTTP
  ApplicationLoadbalancerTargetgroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: vpc-0762271d3be4babdc
#cloudwatch log group
  HostedZoneCloudwathlog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/route53/webapp
      RetentionInDays: 1

#SNS Subscription
  SNSTopics:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Alerts

  SNSSubscripton:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: mohammadhossain109@gmail.com
      Protocol: email
      TopicArn: !Ref SNSTopics
#DNS route 53
HostedZone:
  Type: AWS::Route53::HostedZone
  Properties:
    Name: hossain.com
    QueryLoggingConfig: 
      CloudWatchLogsLogGroupArn: arn:aws:logs:region:account-id:log-group:log_group_name


#need to setup vpc on aws compte