---
AWSTemplateFormatVersion: '2010-09-09'
Description: Basic EC2 instance creation
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06b21ccaeff8cd686
      InstanceType: t2.micro

#must have already a vpc(default)