---
AWSTemplateFormatVersion: 2010-09-09
Description: A sample CloudFormation template with YAML comments.
# Resources section
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: DemoBucket