---
AWSTemplateFormatVersion: 2010-09-09
Description: 'create a custom vpc'
Resources:
  CustomVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True
      Tags: 
        - Key: "name"
          Value: "school"


 
